version: "3"
networks:
  forum.net:
    driver: bridge

services:
  nuxt:
    build:
      context: .
      dockerfile: docker/nuxt
    environment:
      user : ${MARIADB_USER:-user}
      password : ${MARIADB_PASSWORD:-password}
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - forum.net
    command: [ "node", ".output/server/index.mjs" ]
    depends_on:
      - bdd


  bdd:
    image: mariadb
    networks:
      - forum.net
    ports:
      - "3310:3306"
    environment:
      MARIADB_ROOT_PASSWORD : ${MARIADB_ROOT_PASSWORD:-password}
      MARIADB_USER : ${MARIADB_USER:-user}
      MARIADB_PASSWORD : ${MARIADB_PASSWORD:-password}
      MARIADB_DATABASE : forum
    volumes:
      -  ./sql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    networks:
      - forum.net
    ports:
      - "8006:8080"